export const INSTALL_ENV_KEY_COMMENTS: Record<string, string[]> = {
  PORT: ["HTTP port for the Cliodot API process."],
  MONGODB_NAME: ["MongoDB database name used by this instance."],
  MONGODB_URI: ["MongoDB connection string (include auth/replicaSet as needed)."],
  MODE: ["Legacy app mode flag (prefer DEPLOYMENT_MODE)."],
  LOG_LEVEL: [
    "Log verbosity: error | warn | info | debug. Production installs default to error (silences cache/info noise; errors still print).",
  ],
  NODE_ENV: ["Node runtime environment (production for installed instances)."],
  DEPLOYMENT_MODE: [
    "Deployment posture: local | production | enterprise (controls hub publish deny, etc.).",
  ],
  JWT_SECRET: ["Secret used to sign API JWTs. Generated at init — keep private."],
  JWT_EXPIRES_IN: ["Optional JWT lifetime override (e.g. 7d). Empty = server default."],
  SMTP_HOST: ["SMTP host for outbound email (OTP, magic link, notifications)."],
  SMTP_PORT: ["SMTP port (usually 587 or 465)."],
  SMTP_USER: ["SMTP username."],
  SMTP_PASSWORD: ["SMTP password / app password."],
  FROM_EMAIL_ADDRESS: ["From: email address for system mail."],
  FROM_USER_NAME: ["From: display name for system mail."],
  SALT_ROUNDS: ["bcrypt salt rounds for password hashing."],
  AWS_CONTENT_DISPOSITION: ["Optional Content-Disposition for AWS object responses."],
  APP_NAME: ["Human-readable instance / product name."],
  TOKENIZER_SECRET_KEY: ["Secret for tokenizing sensitive connector fields."],
  GOOGLE_CLIENT_ID: ["Google OAuth client id (if using Google login)."],
  REDIS_URL: ["Primary Redis URL (queues, cache, sessions, BullMQ)."],
  EVENT_BROKER_FAST: [
    "Broker for fast/low-latency event delivery profiles (default: bullmq).",
  ],
  EVENT_BROKER_RELIABLE: [
    "Broker for reliable/at-least-once event delivery (default: bullmq).",
  ],
  EVENT_BROKER_ORDERED: [
    "Broker for ordered event delivery (default: redis-streams).",
  ],
  EVENT_BROKER_BROADCAST: [
    "Broker for broadcast-style event fanout (default: bullmq).",
  ],
  EVENT_BROKER_STREAM: [
    "Optional dedicated stream broker override (empty = use profile defaults).",
  ],
  EVENT_BROKER_SCHEDULED: [
    "Broker for scheduled / delayed events (default: bullmq).",
  ],
  KAFKA_BROKERS: ["Comma-separated Kafka brokers (only if a profile uses Kafka)."],
  KAFKA_CLIENT_ID: ["Kafka client id when Kafka brokers are configured."],
  KAFKA_GROUP_ID: ["Kafka consumer group id."],
  KAFKA_TOPIC_PREFIX: ["Prefix applied to Kafka topic names."],
  KAFKA_SSL: ["Enable TLS for Kafka connections (true/false)."],
  KAFKA_SASL_MECHANISM: ["Optional Kafka SASL mechanism."],
  KAFKA_SASL_USERNAME: ["Optional Kafka SASL username."],
  KAFKA_SASL_PASSWORD: ["Optional Kafka SASL password."],
  RABBITMQ_URL: ["RabbitMQ URL (only if a profile uses RabbitMQ)."],
  RABBITMQ_EXCHANGE: ["RabbitMQ exchange name for Cliodot events."],
  RABBITMQ_PREFETCH: ["RabbitMQ consumer prefetch count."],
  RABBITMQ_QUEUE_PREFIX: ["Prefix for RabbitMQ queue names."],
  REDIS_STREAMS_URL: [
    "Redis URL for redis-streams brokers (defaults to REDIS_URL when set).",
  ],
  REDIS_STREAMS_PREFIX: ["Key/stream name prefix for Redis Streams."],
  REDIS_STREAMS_GROUP: ["Consumer group name for Redis Streams."],
  BASE_DOMAIN: ["Base domain used for custom host / SSL features."],
  CLIODOT_CLIENT_URL: ["Public URL of the web client (CORS / redirects)."],
  APP_URL: ["Public URL of this API instance."],
  CLIODOT_BASE_URL: ["Canonical API base URL used by product apps / links."],
  CLIENT_URL: ["Client origin URL written by the installer."],
  SERVER_URL: ["Server origin URL written by the installer."],
  API_BASE_URL: ["API base URL for internal/client wiring."],
  FRONTEND_URL: ["Frontend origin (often same as CLIENT_URL)."],
  STORAGE_TYPE: ["File storage backend: local or aws."],
  MAX_FILE_SIZE: ["Max upload size in bytes for general files."],
  MAX_IMAGE_SIZE: ["Max upload size in bytes for images."],
  AWS_S3_BUCKET: ["S3 bucket when STORAGE_TYPE=aws."],
  AWS_REGION: ["AWS region for S3 / related services."],
  AWS_ACCESS_KEY_ID: ["AWS access key id."],
  AWS_SECRET_ACCESS_KEY: ["AWS secret access key."],
  AWS_S3_BUCKET_URL: ["Public/base URL for objects in the S3 bucket."],
  ENCRYPTION_KEY: [
    "AES key material for connector installation auth / gateway secrets. Generated at init.",
  ],
  DEVICE_TOKEN_SECRET: ["Secret for device token signing."],
  DEVICE_TOKEN_TTL_MS: ["Device token lifetime in milliseconds."],
  WEBHOOK_APP_RECEIVE_RETENTION_MS: [
    "How long received webhook payloads are retained (ms).",
  ],
  SSRF_ALLOW_PRIVATE_URLS: [
    "Allow connectors to call private/LAN IPs (useful for local/dev; keep false on public SaaS).",
  ],
  OUTBOUND_TLS_INSECURE: [
    "Allow invalid/self-signed TLS on outbound connector calls (local/dev only).",
  ],
  GATEWAY_RATE_LIMIT_RPM: [
    "Gateway public endpoint rate limit (requests per minute per client).",
  ],
  LOCAL_UPLOAD_DIR: ["Local filesystem folder for uploads when STORAGE_TYPE=local."],
  LOCAL_PUBLIC_URL: ["Optional public base URL that maps to LOCAL_UPLOAD_DIR."],
  CLOUDINARY_CLOUD_NAME: ["Cloudinary cloud name (if using Cloudinary media)."],
  CLOUDINARY_API_KEY: ["Cloudinary API key."],
  CLOUDINARY_API_SECRET: ["Cloudinary API secret."],
  CLOUDINARY_FOLDER: ["Default Cloudinary folder prefix."],
  FIREBASE_PROJECT_ID: ["Firebase project id (push notifications)."],
  FIREBASE_CLIENT_EMAIL: ["Firebase service account email."],
  FIREBASE_PRIVATE_KEY: ["Firebase service account private key (PEM)."],
  CERT_DIR: ["Directory for ACME/TLS certificates."],
  ACME_EMAIL: ["Email registered with ACME/Let's Encrypt."],
  ACME_STAGING: ["Use ACME staging CA (true) before production certs."],
  DOMAIN_VERIFICATION_SCHEDULE: ["Cron schedule for domain verification jobs."],
  PAYSTACK_SECRET_KEY: ["Paystack secret key (billing)."],
  PAYSTACK_WEBHOOK_SECRET: ["Paystack webhook verification secret."],
  STRIPE_SECRET_KEY: ["Stripe secret key (billing)."],
  STRIPE_WEBHOOK_SECRET: ["Stripe webhook signing secret."],
  FLUTTERWAVE_SECRET_KEY: ["Flutterwave secret key (billing)."],
  FLUTTERWAVE_WEBHOOK_SECRET: ["Flutterwave webhook secret."],
  RAZORPAY_SECRET_KEY: ["Razorpay secret key (billing)."],
  RAZORPAY_WEBHOOK_SECRET: ["Razorpay webhook secret."],
  LICENSE_ENCRYPTION_KEY: [
    "WARNING: Do not alter. Shared license encryption material for activation/validation.",
  ],
  LICENSE_PUBLIC_KEY: [
    "WARNING: Do not alter. Cliodot license signature public key.",
  ],
  BUILD_PRIVATE_KEY: [
    "Build-time private key for integrity manifests (not required at runtime).",
  ],
  SUPPORT_EMAIL: ["Support contact shown for license / ops issues."],
  TELEMETRY_ENABLED: ["Send anonymous telemetry (true/false)."],
  AUTO_CHECK_UPDATES: ["Periodically check for updates (true/false)."],
  CONNECTOR_CACHE_ENABLED: ["Enable general connector definition cache."],
  CONNECTOR_CACHE_TTL: ["Connector cache TTL (ms) when enabled."],
  CONNECTOR_CACHE_MAX_ENTRIES: ["Max entries in connector cache."],
  QUERY_CACHE_ENABLED: ["Enable query result caching."],
  QUERY_CACHE_DB_TTL: ["DB query cache TTL (ms)."],
  QUERY_CACHE_API_TTL: ["API query cache TTL (ms)."],
  QUERY_CACHE_MAX_ENTRIES: ["Max query cache entries."],
  QUERY_CACHE_MAX_SIZE: ["Max query cache size budget."],
  ENV_VARS_CACHE_ENABLED: ["Cache resolved env vars for connectors/workflows."],
  ENV_VARS_CACHE_TTL: ["Env-var cache TTL (ms)."],
  ENV_VARS_CACHE_MAX_ENTRIES: ["Max env-var cache entries."],
  CACHE_BACKEND: ["General cache backend: memory or redis."],
  FAST_RUNTIME_MODE: ["Workflow fast-runtime mode (e.g. legacy)."],
  DEV_RUNTIME_CACHE_ENABLED: ["Enable short-lived runtime cache in development."],
  PROD_ARTIFACT_RUNTIME: ["Use compiled artifacts at runtime in production."],
  PROD_STORE_UI_SNAPSHOT: ["Persist UI snapshots in production builds."],
  DOMAIN_CACHE_TTL: ["Domain metadata cache TTL (ms)."],
  WORKFLOW_HOT_CACHE_MAX_ENTRIES: ["Max hot workflow entries kept in memory."],
  COMPILED_RUNTIME_TTL: ["Compiled runtime cache TTL in production (ms)."],
  COMPILED_RUNTIME_DEV_TTL: ["Compiled runtime cache TTL in development (ms)."],
  CONNECTOR_DEFINITION_CACHE_ENABLED: [
    "Cache immutable connector definitions by version.",
  ],
  CONNECTOR_AUTH_CACHE_ENABLED: [
    "Cache resolved connector auth (headers/tokens) after compile.",
  ],
  CONNECTOR_RUNTIME_CACHE_ENABLED: [
    "Cache fully assembled connector runtime bundles.",
  ],
  CONNECTOR_RUNTIME_STALE_WHILE_REVALIDATE: [
    "Serve last-good runtime past TTL while rebuilding (smoother p99).",
  ],
  CONNECTOR_EXECUTOR_POOL_ENABLED: [
    "Reuse in-process executor metadata per tenant/connector/version.",
  ],
  CONNECTOR_RUNTIME_CACHE_TTL_PROD: ["Connector runtime Redis TTL in prod (ms)."],
  CONNECTOR_RUNTIME_CACHE_TTL_DEV: ["Connector runtime Redis TTL in dev (ms)."],
  CONNECTOR_RUNTIME_CACHE_MAX_ENTRIES: ["Max connector runtime cache entries."],
  CONNECTOR_EXECUTOR_POOL_MAX_ENTRIES: ["Max executor pool entries."],
  CONNECTOR_INSTALLATION_CACHE_ENABLED: [
    "Cache connector installation metadata (auth/base_url) from Mongo.",
  ],
  CONNECTOR_INSTALLATION_CACHE_TTL: ["Installation cache TTL (ms)."],
  WORKFLOW_CACHE_BACKEND: ["Backend for workflow runtime cache (redis recommended)."],
  DOMAIN_CACHE_BACKEND: ["Backend for domain cache (redis recommended)."],
  GATEWAY_CACHE_BACKEND: ["Backend for gateway route cache (redis recommended)."],
  GEMINI_API_KEY: ["Google Gemini API key for AI features."],
  OPENAI_API_KEY: ["OpenAI API key for AI features."],
  ANTHROPIC_API_KEY: ["Anthropic API key for AI features."],
  XAI_API_KEY: ["xAI API key for AI features."],
  DEEPSEEK_API_KEY: ["DeepSeek API key for AI features."],
  GROQ_API_KEY: ["Groq API key for AI features."],
  DEPLOYMENT_ID: ["Unique id for this deployment when talking to the network hub."],
  DEPLOYMENT_REF: ["Public reference URL for this deployment (usually APP_URL)."],
  REMOTE_CONNECTORS_INTEROP_SECRET: [
    "Optional interop secret for remote connector calls (falls back to hub sync key in code).",
  ],
  HUB_CONNECTORS_ENABLED: ["Enable connector hub browse/mirror capabilities."],
  REMOTE_CONNECTORS_ENABLED: ["Enable remote connector federation features."],
  CONNECTOR_EXCHANGE_ENABLED: ["Enable connector exchange features."],
  WORKFLOW_LOG_FLUSH_INTERVAL_MS: [
    "How often workflow logs are flushed to storage (ms).",
  ],
  WORKFLOW_LOG_BATCH_SIZE: ["Max workflow log events per flush batch."],
  AI_COMPRESSION_THRESHOLD: ["Compress AI chat context after N turns."],
  AI_CONTEXT_RECENT_TURNS: ["Recent turns kept uncompressed in AI context."],
  AI_CONTEXT_RETRIEVED_TURNS: ["Retrieved historical turns injected into AI context."],
  AI_CONTEXT_RETRIEVED_CONNECTORS: [
    "Max connectors retrieved into AI scaffold context.",
  ],
  AI_SESSION_TTL_DAYS: ["AI session retention in days."],
  AI_USE_TOOL_CALLING: [
    "Use LLM tool calling for scaffold/generate (false = JSON parse fallback).",
  ],
  CONNECTOR_OAUTH_CALLBACK_URL: [
    "OAuth redirect/callback URL for connector OAuth installs (client origin + /api/connectors/oauth/callback).",
  ],
  OAUTH_APPS_API_HOST: [
    "Public API host used by OAuth Apps (usually the Cliodot API origin).",
  ],
  OAUTH_APPS_ENABLED: ["Feature flag: OAuth Apps product surface."],
  AUTH_APPS_ENABLED: ["Feature flag: Auth Apps product surface."],
  EVENT_APPS_ENABLED: ["Feature flag: Event Apps product surface."],
  MEMORY_APPS_ENABLED: ["Feature flag: Memory Apps product surface."],
  IDENTITY_APPS_ENABLED: ["Feature flag: Identity Apps product surface."],
  WEBHOOK_APPS_ENABLED: ["Feature flag: Webhook Apps product surface."],
  COMMERCIAL_APPS_ENABLED: ["Feature flag: Commercial Apps product surface."],
  GATEWAYS_ENABLED: ["Feature flag: Connector Gateways product surface."],
};
